# Generated by Django 6.0.5 on 2026-07-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_card_options_alter_tasklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['position']},
        ),
    ]
